staging: rtl8723bu: Fix inconsistent teardown and release of private netdev state.
Fixes the following building error:

drivers/staging/rtl8723bu/os_dep/ioctl_cfg80211.c: In function 'rtw_cfg80211_add_monitor_if':
drivers/staging/rtl8723bu/os_dep/ioctl_cfg80211.c:3632:10: error: 'struct net_device' has no member named 'destructor'
  mon_ndev->destructor = rtw_ndev_destructor;
          ^

Caused by commit

  cf124db566e6 ("net: Fix inconsistent teardown and release of private netdev state.")